version: '3'

x-backend-defaults: &backend-common
  image: challenger1304/themenschaedel-backend:nightly
  restart: unless-stopped
  depends_on:
    - database
    - redis
  env_file: .env
  environment: &backend-env
    DB_DATABASE: "${BACKEND_DB_DATABASE:-themenschaedel}"
    DB_USERNAME: "${BACKEND_DB_USERNAME:-themenschaedel}"
    DB_PASSWORD: "${BACKEND_DB_PASSWORD}"
  networks:
    - backend

services:
  app:
    <<: *backend-common
    environment:
      <<: *backend-env
      APP_URL: "https://${HTTP_BASE_DOMAIN:-localhost}"
      SANCTUM_STATEFUL_DOMAINS: "${HTTP_BASE_DOMAIN:-localhost}"
      SESSION_DOMAIN: ".${HTTP_BASE_DOMAIN:-localhost}"
    labels:
      - traefik.enable=true
      - traefik.docker.network=reverse-proxy
      - traefik.http.services.backend.loadbalancer.server.port=8080

      - traefik.http.routers.account.rule=Host(`account.${HTTP_BASE_DOMAIN:-localhost}`)
      - traefik.http.routers.account.tls.certresolver=cloudflare
      - traefik.http.routers.account.entrypoints=https

      - traefik.http.routers.backend.rule=Host(`api.${HTTP_BASE_DOMAIN:-localhost}`)
      - traefik.http.routers.backend.tls.certresolver=cloudflare
      - traefik.http.routers.backend.entrypoints=https
    networks:
      - backend
      - reverse-proxy

  scheduler:
    <<: *backend-common
    depends_on:
      - app
    entrypoint: start scheduler

  worker:
    <<: *backend-common
    depends_on:
      - app
    entrypoint: start worker

  database:
    image: mysql:8.0
    #ports:
    #  - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${BACKEND_DB_PASSWORD}'
      MYSQL_DATABASE: '${BACKEND_DB_DATABASE:-themenschaedel}'
      MYSQL_USER: '${BACKEND_DB_USERNAME:-themenschaedel}'
      MYSQL_PASSWORD: '${BACKEND_DB_PASSWORD}'
    volumes:
      - database:/var/lib/mysql
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

networks:
  backend:
  reverse-proxy:
    external: true

volumes:
  database:
    driver: local
  redis:
    driver: local
