version: '3'

services:
  traefik:
    image: traefik:v2.4
    container_name: schaedel_proxy
    restart: unless-stopped
    command:
      - "--log.level=info"
      - "--api.dashboard=true"
      - "--api.insecure=false"

      - "--entryPoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entryPoint.to=https"
      - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.https.address=:443"
      - "--entrypoints.https.http.tls=true"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=reverse-proxy"
    labels:
      - traefik.enable=true
      - traefik.http.routers.proxy.rule=Host(`traefik.${HTTP_BASE_DOMAIN:-localhost}`)
      - traefik.http.routers.proxy.entrypoints=https
      - traefik.http.routers.proxy.service=api@internal
    networks:
      - reverse-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  reverse-proxy:
    external: true

volumes:
  traefik:
    driver: local
