version: '3'

services:
  api-docs:
    image: challenger1304/themenschaedel-api-docs:latest
    restart: unless-stopped
    container_name: schaedel_api_docs
    labels:
      - traefik.enable=true
      - traefik.docker.network=reverse-proxy
      - traefik.http.services.api-docs.loadbalancer.server.port=8080

      - traefik.http.routers.api-docs.rule=Host(`api.docs.${HTTP_BASE_DOMAIN:-localhost}`)
      - traefik.http.routers.api-docs.tls.certresolver=cloudflare
      - traefik.http.routers.api-docs.entrypoints=https
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
